---
openapi: 3.0.1
info:
  title: Jibber-Jabber Followers V1
  version: v1
paths:
  "/":
    get:
      summary: list follows
      responses:
        '200':
          description: successful
  "/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    post:
      summary: toggle follow
      responses:
        '200':
          description: successful
    get:
      summary: show follow
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
