default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['LOCAL_POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: jj_follow_development


test:
  <<: *default
  database: jj_follow_test
  

