name: CD - Prod

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t jibber-jabber-follows-prod .

      - name: Tags
        run: |
          docker tag jibber-jabber-follows-prod ${{ secrets.DOCKER_USER }}/jibber-jabber-follows-prod:${{ github.sha }}
          docker tag jibber-jabber-follows-prod ${{ secrets.DOCKER_USER }}/jibber-jabber-follows-prod:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-follows-prod:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-follows-prod:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_PROD_USER }}
          SSH_KEY: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_PROD_HOST }}

      - name: Stop the server
        run: ssh prod 'docker-compose stop'

      - name: Remove container and image
        run: ssh prod 'docker container rm followers && docker image rm georgesstefan/jibber-jabber-follows-prod'

      - name: Pull new image
        run: ssh prod 'docker pull ${{ secrets.DOCKER_USER }}/jibber-jabber-follows-prod:${{ github.sha }}'

      - name: Start the server
        if: ${{ always() }}
        run: ssh prod 'docker-compose up -d > /dev/null 2>&1'